export let survivalDrops = [
  {
    y: 100,
    x: 400,
    width: 40,
    height: 40,
    img: "assets/images/XP.png",
    type: "xp",
    value: 3000,
    isActive: true,
  },
  //   {
  //     y: 200,
  //     x: 200,
  //     width: 40,
  //     height: 40,
  //     img: "assets/images/XP.png",
  //     type: "xp",
  //     value: 1000,
  //   },
  //   {
  //     y: 300,
  //     x: 400,
  //     width: 40,
  //     height: 40,
  //     img: "assets/images/XP.png",
  //     type: "xp",
  //     value: 1000,
  //   },
  //   {
  //     y: 600,
  //     x: 300,
  //     width: 40,
  //     height: 40,
  //     img: "assets/images/XP.png",
  //     type: "xp",
  //     value: 1000,
  //   },
  //   {
  //     y: 500,
  //     x: 200,
  //     width: 40,
  //     height: 40,
  //     img: "assets/images/XP.png",
  //     type: "xp",
  //     value: 1000,
  //   },
];
